### ISSUE TITLE
Resolver doesn't work without timeout: "there is no address available" error

### ISSUE THREAD

**Issue by vadiminshakov** [nicholasjackson/grpc-consul-resolver#1]
Without **sleep** between call `resolver.NewServiceQueryResolver()` and `grpc.Dial()` I get error: `there is no address available`. But with `sleep` all works fine, here is an example:

```
r := resolver.NewServiceQueryResolver("consuladdr:8500")
	lb := grpc.RoundRobin(r)

	time.Sleep(10 * time.Second)

	c, err := grpc.Dial(
		"service",
		grpc.WithInsecure(),
		grpc.WithBalancer(lb),
	)

	return c, err
```

**Comment by VadimInshakov** [comment]
But after service health-check-ping there is no need to wait for N seconds.

**Comment by vadiminshakov** [comment]
It's was my mistake, closing.
